### ISSUE TITLE
error in version check of maven in build.sh

### ISSUE THREAD

**Issue by holgerjakobs** [zalando/PGObserver#59]
The command gathering the Maven version in build.sh should read
MAVEN_VERSION=$(mvn --version |  grep -o '3\.' | head -n 1)

The original (with head first and then grep) writes "3.\n3." into the variable which is different from "3."

**Comment by kmoppel** [comment]
Hi, thanks for the report!
But for me (Ubuntu+Bash 4.3.11) actually the output ("3.") seems correct...what kind of system are you using? Maybe we can make it more universal indeed.

**Comment by Pelleplutt** [comment]
Yeah it does. It doesn't however if JAVA_HOME is not set, wild guess that this could be the root cause for OP's problem:

autodeploy@test:~/src/PGObserver$ mvn --version
Warning: JAVA_HOME environment variable is not set.
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_95, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-51-generic", arch: "amd64", family: "unix"

**Comment by kmoppel** [comment]
@Pelleplutt Hi. Couldn't grasp the context of your comment:) Is there something that's not working for you?

**Comment by Pelleplutt** [comment]
@kmoppel my message was related to the issue reported by @holgerjakobs about version numbering. All is fine for me. But reading this thread less hastily now I see that it was premature. Please ignore.
